{
 "title": "Historian-Backend",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate by route",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"historian-backend\"}[5m])) by (instance, route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Requests over time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_total{job=\"historian-backend\"}",
     "legendFormat": "{{method}} - {{route}} - {{status}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_system_seconds_total{job=\"historian-backend\"}[1m])"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total{job=\"historian-backend\"}[1m])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"historian-backend\"}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"historian-backend\"}"
    }
   ]
  }
 ]
}