name: (Backend) Build and Test

on:
    push:
        paths:
            - src/backend/**
        branches: [master]
    pull_request:
        branches: [master]
        paths:
            - src/backend/**

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2
            - name: Setup PostgreSQL
              uses: Harmon758/postgresql-action@v1.0.0
              with:
                  postgresql version: 12
                  postgresql db: historian
                  postgresql user: postgres
                  postgresql password: password
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Build and test backend
              working-directory: ./src/backend
              run: |
                  pwd
                  npm install
                  npm test
