name: (Frontend) Deploy

on:
    push:
        paths:
            - src/frontend/**
        branches: [master]
    pull_request:
        branches: [master]
        paths:
            - src/frontend/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Deploy Frontend to Askari
              uses: JimCronqvist/action-ssh@0.1.1
              with:
                  hosts: ${{ secrets.SSH_TARGET }}
                  privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
                  debug: false
                  command: |
                      /home/arkits/software/historian/src/frontend/scripts/deploy.sh
